services:
    nassim.avatar.listener:
        class: nassim\topic_avatar\event\main
        arguments:
            - @dbal.conn
            - @config
            - @template
            - @request
            - @user
        tags:
            - { name: event.listener }
            